# This override file allows using locally built images
# It takes precedence over docker-compose.yaml

services:
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    image: dify-web:local