# This override file allows using locally built images
# It takes precedence over docker-compose.yaml

services:
  # Replace web service with a dummy container that does nothing
  # This satisfies nginx's dependency while allowing local development
  web:
    image: alpine:latest
    command: ["sh", "-c", "echo 'Web service disabled for local development' && sleep infinity"]
    restart: always
  
  # Configure nginx to proxy to local development server
  nginx:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Override to prevent default.conf.template from being used
      NGINX_PORT: 80
      NGINX_SERVER_NAME: _
    volumes:
      # Use our custom configuration instead of the template
      - ./nginx/conf.d/default-local-dev.conf:/etc/nginx/conf.d/default.conf