# This override file allows using locally built images
# It takes precedence over docker-compose.yaml

services:
  # API service with local build
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    image: dify-api:local
    restart: always
  
  # Worker service using the same locally built image
  worker:
    build:
      context: ../api
      dockerfile: Dockerfile
    image: dify-api:local
    restart: always
  
  # Worker beat service using the same locally built image
  worker_beat:
    build:
      context: ../api
      dockerfile: Dockerfile
    image: dify-api:local
    restart: always
  
  # Web service with local build
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    image: dify-web:local
    restart: always
  
  # Configure nginx to proxy to local development server
  nginx:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Override to prevent default.conf.template from being used
      NGINX_PORT: 80
      NGINX_SERVER_NAME: _
    volumes:
      # Use our custom configuration instead of the template
      - ./nginx/conf.d/default-local-dev.conf:/etc/nginx/conf.d/default.conf